# fly.toml app configuration file generated for watermelon on 2024-08-03T21:57:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'watermelon'
primary_region = 'ord'

[build]

[env]
  DISCORD_TOKEN = 'PLACEHOLDER'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
