name: Perform Formatter and Linter Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_quality_analysis:
    name: Perform Formatter and Linter Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Source Code
        uses: actions/checkout@v4

      - name: Install Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: "latest"

      - name: Execute Formatter and Linter Check
        run: biome ci .
